### ISSUE TITLE
Clarification of the specific fields in the BlockChain

### ISSUE THREAD

**Issue by markpyzhov** [MallCloud/contracts-api#16]
The original text of requirements is described in [wiki/BlockChain-communication](https://github.com/MallCloud/contracts-api/wiki/BlockChain-communication#business-requirements).

> - Access to specific fields in the data.  This requires the field to be linked to the dataset using the hashed version function of Kapil's api; and requires registration of the field on blockchain

Few questions:
1. What does mean *"using the hashed version function of Kapil's api"*?
2. How the specific fields can be registered in the Blockchain and why?
3. How are specific fields will be used via Blockchain?

**Comment by ehillerbrand** [comment]
@daemonslayer 's API created a way of creating chains of versions using hashkeys.  Therefore, we have situation as follows:

![pricing](https://user-images.githubusercontent.com/15766155/31632016-2159e2ee-b281-11e7-9306-6292c318ebf1.png)

Suppose a user doesn't want to buy a whole dataset but wants to buy just a field; or a user wants to sell field by field and not sell the whole dataset.

Since we would be selling by the field, we would need to track the transactions on blockchain.

**Comment by markpyzhov** [comment]
From @daemonslayer:

> We can perform that in such way. The dataset could be broken up and then sold by using blockchains. The hash part is not needed though as blockchain performs all required hashing by itself.

Few questions:

1. By "Canonical Solution" you mean Canonical Pipeline?
2. DataSet might contain hundreds fields. Are these costs fine?
3. As I understand commonly each train algorithm uses an input and an output (actual vector, which will be compared with prediction). So as minimum two fields for training (if I'm wrong, please tell me). Does someone might need for only single one field yet?

I would like to propose different way instead of Field registration in BlockChain (actually I originally designed it in the [wiki/BlockChain-communication](https://github.com/MallCloud/contracts-api/wiki/BlockChain-communication#business-requirements)):
1. In PostgreSQL we have:
    - Solution (full-schema)
    - SubSolution (two or more fields from the schema)
    - DataSet (commonly covers full schema of Solution)
    - RFS (belongs to Solution OR SubSolution)
2. In Contracts API (BlockChain):
    - DataSet 
    - RFS
3. If someone wants to purchase specific fields I think we can operate by SubSolution schema (via RFS), which might contain only two or more fields from full DataSet.

**Comment by kgupta15** [comment]
The fields can be considered as metadata for Dataset that can be defined separately in IPFS. That will require blockchain to only store URL instead of storing thousands of fields, reducing costs.

The requirement is regarding dataset which is different from input and output vectors for an algorithm. The vectors you mention are constructed using dataset and dataset itself doesn't have them from beginning.

**Comment by markpyzhov** [comment]
> can be defined separately in IPFS

What is IPFS?

> The vectors you mention are constructed using dataset and dataset itself doesn't have them from beginning.

Why do you think so? I meant any data including Canonical, from Customer.

**Comment by kgupta15** [comment]
IPFS : InterPlanetary File System
https://ipfs.io
This filesystem is designed to work well in decentralized and blockchain based systems.


The input and output values are designed according to algorithm. Some algorithms need specific output structure like Neural Nets. Similarly some need specific input structure like NMF. So dataset may be unstructured or structured(different from i/o vectors), it doesn't matter. Data is restructured for each algo.

**Comment by markpyzhov** [comment]
> IPFS : InterPlanetary File System
https://ipfs.io
This filesystem is designed to work well in decentralized and blockchain based systems.

It was a surprise for me that we are going to use an additional tool. Can you draw scheme, what components and how do they work on your side?

> The input and output values are designed according to algorithm. Some algorithms need specific output structure like Neural Nets. Similarly some need specific input structure like NMF. So dataset may be unstructured or structured(different from i/o vectors), it doesn't matter. Data is restructured for each algo.

I think we are losing topic. The question was: *"Does someone might need for only single one field yet?"*

**Comment by kgupta15** [comment]
I am not sure why this was a surprise. This is neither a new tool nor does it have many components. If you remember blockchainDB that was considered as a storage medium for data (and was found insufficient because limits on data storage capacity) you will find that it is based on IPFS, something I had mentioned too. IPFS is a storage medium which is supported by blockchain and hence allows easy checkup directly from blockchain. This allows more open structure. Also, since contracts are limited in storage by design, IPFS is the most common way to store more data easily. Hence, it was considered that the metadata that is too much for contracts will be stored in IPFS and URL of IPFS stored in contract. 

IPFS uses similar node like structure and hashes all the information stored as well as the location of this information. The hash is connected to ethereum blockchain. 

In the current system, small details like name of notebook etc are present in contract. The contracts which will have much more information like 1000's of fields will have to be stored in IPFS. The url of IPFS will then be stored in the contract allowing client to easily verify the presence and correctness of data.


Yes, someone might need single fields too. If there is some flight data and they just want to enhance the data with one field that might help in getting the output, it might be useful to get it. I can agree though that this will be less common but buying 2-3 fields or few fields in count is very common.

**Comment by markpyzhov** [comment]
> Yes, someone might need single fields too. If there is some flight data and they just want to enhance the data with one field that might help in getting the output, it might be useful to get it. I can agree though that this will be less common but buying 2-3 fields or few fields in count is very common.

One more time. Please, explain the case when single one field is useful. Just wanted to understand the possible situations.

**Comment by kgupta15** [comment]
Please remember that just one field is never going to be used in the machine learning algorithm. The statement is regarding selling of one field and not using just one or a few fields in the algorithm.

So think it like this: you already have a big dataset with many fields available. There is another dataset with some similar and some different fields and one of the fields from the new dataset can be used to enhance the original dataset and get better predictions. This means that you will like to buy that one field.

**Comment by markpyzhov** [comment]
Yes, I agree with that.
